export const quizTopics = [
  "World Capitals",
  "Olympic Sports",
  "Famous Authors",
  "Historical Events",
  "Space Exploration",
  "Movie Trivia",
  "Musical Instruments",
  "Animal Kingdom",
  "Chemical Elements",
  "Famous Paintings",
  "World Cuisines",
  "Computer Programming",
  "Classical Music",
  "Mythology",
  "Board Games",
  "Environmental Science",
  "Nobel Prize Winners",
  "Mathematical Concepts",
  "Shakespeare's Plays",
  "Renewable Energy",
  "World Religions",
  "Human Anatomy",
  "Literary Genres",
  "Physics Laws",
  "Ancient Civilizations",
  "Modern Technologies",
  "Famous Landmarks",
  "Astronomy",
  "Psychology Theories",
  "Geographical Features",
  "International Politics",
  "Philosophical Concepts",
  "Fashion History",
  "Famous Scientists",
  "Children's Literature",
  "Economic Theories",
  "Biology",
  "Film Directors",
  "Classical Composers",
  "Languages of the World",
  "Architectural Styles",
  "Sports Personalities",
  "Historical Figures",
  "Computer Games",
  "Opera",
  "Famous Battles",
  "Periodic Table",
  "Inventions",
  "World Leaders",
  "Mythical Creatures",
  "Solar System",
  "Botany",
  "Famous Poems",
  "Marine Biology",
  "NBA Teams",
  "Art Movements",
  "Geology",
  "Famous Bridges",
  "Endangered Species",
  "Nobel Laureates",
  "Musical Genres",
  "National Parks",
  "Chess Grandmasters",
  "Medieval History",
  "Computer Science",
  "Jazz Musicians",
  "Famous Explorers",
  "Archaeology",
  "TV Series",
  "Booker Prize Winners",
  "Quantum Physics",
  "Famous Inventors",
  "Zoology",
  "Tourist Attractions",
  "Climate Change",
  "Famous Comedians",
  "African Countries",
  "Dinosaurs",
  "Graphic Novels",
  "Classical Mythology",
  "Music Theory",
  "Famous Buildings",
  "Great Composers",
  "Digital Technology",
  "Culinary Arts",
  "American Presidents",
  "World Literature",
  "Astronauts",
  "Social Media Platforms",
  "Nuclear Physics",
  "Photography",
  "Cartography",
  "Philosophers",
  "Modern Art",
  "Historic Expeditions",
  "Cryptography",
  "Broadway Musicals",
  "Aviation History",
  "Famous Architects",
  "Greek Mythology",
  "Video Game History",
  "Animal Behavior",
  "Asian Cuisine",
  "Film Genres",
  "Ecology",
  "Classical Ballet"
]
